using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Portcullis.Api.Data;
using Portcullis.Api.Domain.Entities;
using Testcontainers.PostgreSql;

namespace Portcullis.Api.Tests.Data.Configuration;

public class UserConfigurationTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("postgres:17-alpine").Build();

    public async ValueTask InitializeAsync() => await _postgres.StartAsync();
    public async ValueTask DisposeAsync() => await _postgres.DisposeAsync();

    private PortcullisDbContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<PortcullisDbContext>()
            .UseNpgsql(_postgres.GetConnectionString())
            .Options;

        return new PortcullisDbContext(options);
    }

    [Fact]
    public async Task User_Id_IsPrimaryKey_NotAutoGenerated()
    {
        await using var context = CreateContext();
        await context.Database.EnsureCreatedAsync(TestContext.Current.CancellationToken);

        var property = context.Model
            .FindEntityType(typeof(User))!
            .FindProperty(nameof(User.Id))!;

        Assert.True(property.IsPrimaryKey());
        Assert.Equal(ValueGenerated.Never, property.ValueGenerated);
    }
}
